# Generated by Django 3.2.5 on 2021-08-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('num_client', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=15)),
                ('how_connu', models.TextField()),
                ('date_dappel', models.DateField()),
                ('heure_dappel', models.TextField(default='', null=True)),
                ('date_arrivee', models.DateField(default='12-09-2030', null=True)),
                ('article_dinteret', models.TextField()),
                ('date_redezvous', models.DateTimeField()),
                ('heure_redezvous', models.TimeField()),
                ('status', models.TextField(default='', null=True)),
                ('heure_arrivee', models.TextField()),
            ],
        ),
    ]
