# Generated by Django 3.2.5 on 2021-08-17 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='Paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.paiement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
