# Generated by Django 3.2.5 on 2021-08-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientappel',
            name='article_interet',
            field=models.CharField(default='maison', max_length=60),
        ),
        migrations.AddField(
            model_name='clientappel',
            name='date_rendezvous',
            field=models.DateField(default=None),
        ),
    ]
