# Generated by Django 3.2.5 on 2021-08-15 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='somme',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facture',
            name='User_editeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.article'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='num_facture',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
