# Generated by Django 3.2.5 on 2021-08-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210817_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='Paiement',
        ),
    ]
