# Generated by Django 3.2.5 on 2021-08-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210818_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='accompte',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_achat',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_dernier_paiement',
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_piece_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
