# Generated by Django 3.2.5 on 2021-08-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210802_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.societe'),
        ),
    ]
