# Generated by Django 3.2.5 on 2021-08-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_client_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='penalty_somme',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facture',
            name='penalty_status',
            field=models.BooleanField(default=False),
        ),
    ]
