# Generated by Django 3.2.5 on 2021-08-17 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_client_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='emetteur',
        ),
        migrations.AddField(
            model_name='credit',
            name='societe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.societe'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.credit'),
        ),
        migrations.AddField(
            model_name='facture',
            name='penalty_somme',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facture',
            name='penalty_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='frais_montage',
            field=models.FloatField(default=15000),
        ),
        migrations.AlterField(
            model_name='credit',
            name='accompte',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='apport',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.article'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='autre_frais',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_emission',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_fin',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_signature',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='frais_dossier',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='montant',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='somme_payee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='subvention',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='taux',
            field=models.FloatField(default=0),
        ),
    ]
