# Generated by Django 3.2.5 on 2021-08-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210820_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.societe'),
        ),
        migrations.AddField(
            model_name='article',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.societe'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
