# Generated by Django 3.2.5 on 2021-09-08 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210821_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='somme_payee',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_arrivee',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
