# Generated by Django 3.2.5 on 2021-08-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210816_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_dernier_paiement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
