# Generated by Django 3.2.5 on 2021-09-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210908_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='penalite',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
