# Generated by Django 3.2.5 on 2021-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_client_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_emission',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_signature',
            field=models.DateField(default=None),
        ),
    ]
