# Generated by Django 3.2.5 on 2021-09-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210908_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='somme_payee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='credit',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
