# Generated by Django 3.2.5 on 2021-08-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='localisation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='nom',
            field=models.CharField(default='N/A', max_length=60),
        ),
    ]
