# Generated by Django 3.2.5 on 2021-08-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210817_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_emission',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_signature',
            field=models.DateField(default=None, null=True),
        ),
    ]
