# Generated by Django 3.2.5 on 2021-08-17 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210817_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_emission',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_fin',
            field=models.DateField(blank=True, default=None),
        ),
    ]
