# Generated by Django 3.2.5 on 2021-08-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210803_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True, verbose_name='Email Ad  dress'),
        ),
    ]
