# Generated by Django 3.2.5 on 2021-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210817_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_fin',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
