# Generated by Django 3.2.5 on 2021-07-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.IntegerField(default=0)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=60)),
                ('poste', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=False)),
                ('date_creation', models.DateField()),
            ],
        ),
    ]
